// cmd_analyze.go — analyze subcommand
//
// Loads recon_dump.json, prints the AI analysis trigger, and optionally
// generates .claude_actions.sh with copy-pasteable probe commands.
//
// Flags:
//   --fast    Format for Haiku "mass triage" mode (tag 100 IPs quickly)
//             Default is deep Lead Researcher mode for Sonnet/Opus.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"strings"
)

func cmdAnalyze(args []string) {
	fs := flag.NewFlagSet("analyze", flag.ContinueOnError)
	fs.SetOutput(os.Stderr)
	fast := fs.Bool("fast", false, "Haiku mass-triage mode (quick tag: Boring/Interesting/Critical)")
	if err := fs.Parse(args); err != nil {
		os.Exit(1)
	}

	raw, err := os.ReadFile(dumpFile)
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: could not read %s: %v\n", dumpFile, err)
		fmt.Fprintln(os.Stderr, "hint: run 'goharvester hunt <query>' first")
		os.Exit(1)
	}

	var summary struct {
		Query     string            `json:"query"`
		Timestamp string            `json:"timestamp"`
		Returned  int               `json:"returned"`
		Hosts     []json.RawMessage `json:"hosts"`
	}
	if err := json.Unmarshal(raw, &summary); err != nil {
		fmt.Fprintf(os.Stderr, "error: could not parse %s: %v\n", dumpFile, err)
		os.Exit(1)
	}

	// Parse hosts for action file generation
	type hostStub struct {
		IP        string   `json:"ip_str"`
		Port      int      `json:"port"`
		Hostnames []string `json:"hostnames"`
	}
	var hosts []hostStub
	for _, raw := range summary.Hosts {
		var h hostStub
		json.Unmarshal(raw, &h)
		hosts = append(hosts, h)
	}

	hostCount := len(summary.Hosts)

	fmt.Printf("DATA LOADED: %d hosts found.\n\n", hostCount)
	fmt.Printf("  source   : %s\n", dumpFile)
	fmt.Printf("  query    : %s\n", summary.Query)
	fmt.Printf("  captured : %s\n", summary.Timestamp)
	fmt.Printf("  hosts    : %d\n\n", hostCount)

	if *fast {
		// ── Haiku mass-triage prompt ──────────────────────────────────────
		fmt.Println("MODE: FAST TRIAGE (Claude Haiku)")
		fmt.Println(strings.Repeat("─", 60))
		fmt.Printf(`Claude, perform a FAST MASS TRIAGE on the %d hosts in %s.
For each host output ONE LINE:
  [IP:PORT] [TAG] [one-sentence reason]
Tags: CRITICAL | INTERESTING | BORING
Rules:
  CRITICAL  = exposed admin panel, unauth service, expired cert on internal CA, open docker socket
  INTERESTING = non-standard port, version-disclosed old product, shadow-IT indicator
  BORING    = CDN IP, standard nginx 200, well-known cloud LB
Finish with a 3-row table: IP | Tag | Top probe command.
`, hostCount, dumpFile)
	} else {
		// ── Deep research prompt ──────────────────────────────────────────
		fmt.Println("MODE: DEEP LEAD RESEARCHER ANALYSIS (Sonnet/Opus)")
		fmt.Println(strings.Repeat("─", 60))
		fmt.Printf("Claude, please perform a Lead Researcher Analysis on this data now.\n")
		fmt.Printf("Apply all Nuance Checks from CLAUDE_PROJECT_CONTEXT.md.\n")
		fmt.Printf("Conclude with the Top 3 High-Value Targets table and active probe commands.\n\n")

		fmt.Println("── AI/LLM Indicator Checks ──────────────────────────────────────────────")
		fmt.Println("If any hosts serve AI/ML infrastructure, apply these additional checks:")
		fmt.Println("  /v1/models on port 8000/11434 → inference server, check for unauthenticated model listing")
		fmt.Println("  /api/v1/collections → unauthenticated vector DB (ChromaDB pattern)")
		fmt.Println("  /api/v1/prompts → exposed LLM gateway or prompt management service")
		fmt.Println("  'NVIDIA' or 'DCGM' in banner → GPU compute dashboard, look for /metrics exposure")
		fmt.Println("  Flowise /api/v1/chatflows or /api/v1/tools → LLM orchestration, check for unauth create/delete")
		fmt.Println("")

		fmt.Println("── Lateral Movement Check ───────────────────────────────────────────────")
		fmt.Println("After identifying top targets, look for trust relationships between hosts:")
		fmt.Println("  Shared SSL serial numbers → provisioned from same PKI template (single logical cluster)")
		fmt.Println("  Common ISP + overlapping hostname patterns → pivot opportunity")
		fmt.Println("  If AI/LLM server found behind Menlo Gateway → flag [CRITICAL: PROTECTED AI INFRA] and probe for bypass")
		fmt.Println("Would you like me to look for 'Lateral Movement' opportunities between these hosts?")
	}

	// ── Generate .claude_actions.sh ───────────────────────────────────────
	// Produces a shell script with the exact goprobe and curl commands for
	// the first 3 hosts. Claude Code can `cat` and execute this directly.
	actionsFile := ".claude_actions.sh"
	var sb strings.Builder
	sb.WriteString("#!/usr/bin/env bash\n")
	sb.WriteString("# Auto-generated by goharvester analyze\n")
	sb.WriteString("# Claude: cat this file and execute the commands inside.\n\n")

	limit := 3
	if len(hosts) < limit {
		limit = len(hosts)
	}
	for i, h := range hosts[:limit] {
		sb.WriteString(fmt.Sprintf("# ── Target %d: %s:%d ──\n", i+1, h.IP, h.Port))
		if len(h.Hostnames) > 0 {
			hostnameArgs := strings.Join(h.Hostnames, " ")
			sb.WriteString(fmt.Sprintf("~/goprobe/goprobe %s %s\n", h.IP, hostnameArgs))
			for _, hn := range h.Hostnames {
				sb.WriteString(fmt.Sprintf("curl -sk --resolve '%s:%d:%s' 'https://%s/' -I\n", hn, h.Port, h.IP, hn))
			}
		} else {
			sb.WriteString(fmt.Sprintf("curl -sk 'https://%s:%d/' -I\n", h.IP, h.Port))
		}
		sb.WriteString("\n")
	}

	if err := os.WriteFile(actionsFile, []byte(sb.String()), 0755); err != nil {
		fmt.Fprintf(os.Stderr, "warn: could not write %s: %v\n", actionsFile, err)
	} else {
		fmt.Printf("\nACTIONS GENERATED. Claude, please `cat %s` and execute the commands inside to begin active probing.\n", actionsFile)
	}
}
